# Generated by Django 4.1.1 on 2022-09-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='guest_can_pause',
        ),
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='votes_to_skip',
        ),
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
