# Generated by Django 4.1.1 on 2022-10-16 22:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_remove_room_code_remove_room_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('mail', models.EmailField(default='', max_length=100)),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(blank=True, choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler')], max_length=10)),
                ('marca', models.CharField(default='', max_length=100)),
                ('matricula', models.CharField(default='', max_length=100, unique=True)),
                ('precio_base', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='api/image_vehiculo')),
                ('vendedor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo')),
                ('comprador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.comprador')),
            ],
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('comprador', 'vehiculo'), name='unique_comprador_vehiculo_combination'),
        ),
    ]
