# Generated by Django 4.1.1 on 2022-10-23 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_comprador_vendedor_vehiculo_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprador',
            old_name='id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='precio_base',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedor'),
        ),
    ]
