# Generated by Django 4.1.1 on 2022-10-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_id_comprador_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='precio_base',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
    ]
