# Generated by Django 4.1.1 on 2022-10-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vehiculo_precio_base_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='api/image_vehiculo'),
        ),
    ]
