# Generated by Django 4.1.1 on 2022-10-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_mail_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comprador'),
        ),
        migrations.AlterField(
            model_name='like',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo'),
        ),
    ]
