# Generated by Django 4.1.1 on 2022-11-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.CharField(max_length=100)),
                ('enviado_por', models.CharField(choices=[('Comprador', 'Comprador'), ('Vendedor', 'Vendedor')], max_length=10)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chat')),
            ],
        ),
    ]
