# Generated by Django 4.1.1 on 2022-11-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='enviado_por',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor')], max_length=10),
        ),
    ]
